apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
  resourceNames: ["orange", "blue"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
