apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulato
    name: webapp
    volumeMounts:
    - mountPath: /log
      name: webapp
  volumes:
  - name: webapp
    hostPath:
      # directory location on host
      path: /var/log/webapp
      # this field is optional
      type: Directory