#kubectl create/apply -f template.yaml 
apiVersion: v1 / apps/v1
kind: Pod / Service / ReplicaSet / Deployment
metadata:
  name: pod-name
  labels:
    app: kasnxa
    tier: front
    type: prod
spec:
  serviceAccountName: "service-account"
  containers:
    - name: nginx
      image: nginx #Please write the full name of the container in case it's not hosted in docker and also you need to write down the version ex: nginx:latest
    - name: busybox
      image: busybox:latest
  tolerations:
    - key: "app"
      operator: "="
      value: "blue"
      effect: "NoSchedule"
  nodeSelector:
    size: large
  affinity:
    nodeAffinity:
      required DuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In / NotIn / Exists
            values:
            - Large
            - small
