apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: kasnxa
    tier: front
    type: prod
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox