apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: kasnxa
    tier: front
    type: prod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
          name: app-config
        - secretRef:
            name: app-secret
    - name: busybox
      image: busybox